name: BUSTED_ModelTest
channels:
  - conda-forge
  - bioconda
  - defaults

dependencies:
  - biopython=1.78
  - hyphy=2.5.42
  - snakemake=7.15.2
  - python=3.9
  - jupyter=1.0
  - jupyterlab_code_formatter=1.5.3